using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Jellyfin.Plugin.StartupAds.Configuration;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.StartupAds.Services
{
    /// <summary>
    /// Owns advertisement CRUD, automatic scanning and the "which ads are active now"
    /// selection logic. Stateless beyond the plugin configuration.
    /// </summary>
    public class AdvertisementManager
    {
        private readonly ILogger<AdvertisementManager> _logger;
        private readonly MediaFileService _files;

        public AdvertisementManager(ILogger<AdvertisementManager> logger, MediaFileService files)
        {
            _logger = logger;
            _files = files;
        }

        private static PluginConfiguration Config =>
            Plugin.Instance?.Configuration ?? new PluginConfiguration();

        private static void Save()
        {
            if (Plugin.Instance is { } p)
            {
                p.SaveConfiguration();
            }
        }

        public IReadOnlyList<Advertisement> GetAll() => Config.Advertisements.ToList();

        public Advertisement? Get(Guid id) => Config.Advertisements.FirstOrDefault(a => a.Id == id);

        public Advertisement Create(Advertisement ad)
        {
            var cfg = Config;
            if (ad.Id == Guid.Empty)
            {
                ad.Id = Guid.NewGuid();
            }

            if (ad.Order == 0)
            {
                ad.Order = cfg.Advertisements.Count == 0 ? 1 : cfg.Advertisements.Max(a => a.Order) + 1;
            }

            cfg.Advertisements.Add(ad);
            Save();
            _logger.LogInformation("[StartupAds] Advertisement created: {Name}", ad.Name);
            return ad;
        }

        public Advertisement? Update(Advertisement ad)
        {
            var cfg = Config;
            var idx = cfg.Advertisements.FindIndex(a => a.Id == ad.Id);
            if (idx < 0)
            {
                return null;
            }

            cfg.Advertisements[idx] = ad;
            Save();
            _logger.LogInformation("[StartupAds] Advertisement updated: {Name}", ad.Name);
            return ad;
        }

        public bool Delete(Guid id)
        {
            var cfg = Config;
            var removed = cfg.Advertisements.RemoveAll(a => a.Id == id) > 0;
            if (removed)
            {
                cfg.Statistics.RemoveAll(s => s.AdvertisementId == id);
                Save();
                _logger.LogInformation("[StartupAds] Advertisement deleted: {Id}", id);
            }

            return removed;
        }

        public Advertisement? Duplicate(Guid id)
        {
            var src = Get(id);
            if (src is null)
            {
                return null;
            }

            var clone = new Advertisement
            {
                Id = Guid.NewGuid(),
                Name = src.Name + " (copia)",
                Type = src.Type,
                Title = src.Title,
                Description = src.Description,
                MediaFile = src.MediaFile,
                BackgroundFile = src.BackgroundFile,
                DurationMode = src.DurationMode,
                DurationSeconds = src.DurationSeconds,
                Priority = src.Priority,
                Order = 0,
                Enabled = false,
                ShowOnStartup = src.ShowOnStartup,
                AllowSkip = src.AllowSkip,
                SkipAfterSeconds = src.SkipAfterSeconds,
                ShowCountdown = src.ShowCountdown,
                ButtonText = src.ButtonText,
                ButtonAction = src.ButtonAction,
                ButtonUrl = src.ButtonUrl,
                ButtonItemId = src.ButtonItemId,
                ObjectFit = src.ObjectFit,
                StartDate = src.StartDate,
                EndDate = src.EndDate,
                DaysOfWeek = new List<int>(src.DaysOfWeek),
                StartTime = src.StartTime,
                EndTime = src.EndTime,
                AllowedUserIds = new List<string>(src.AllowedUserIds),
                AutoGenerated = false
            };

            return Create(clone);
        }

        public bool SetEnabled(Guid id, bool enabled)
        {
            var ad = Get(id);
            if (ad is null)
            {
                return false;
            }

            ad.Enabled = enabled;
            Save();
            return true;
        }

        public class ScanResult
        {
            public int Imported { get; set; }

            public int RemovedMissing { get; set; }
        }

        /// <summary>
        /// Reconciles the auto-generated advertisements with the files on disk:
        /// creates one ad per new compatible file, and removes auto-generated ads whose
        /// file has disappeared. Manually-created ads are never touched.
        /// </summary>
        public ScanResult ScanAndImport()
        {
            var cfg = Config;
            var files = _files.ListFiles(cfg.AdsDirectory);
            var result = new ScanResult();

            var onDisk = new HashSet<string>(files.Select(f => f.FileName), StringComparer.OrdinalIgnoreCase);

            // 1. Prune auto-generated ads whose file no longer exists.
            var stale = cfg.Advertisements
                .Where(a => a.AutoGenerated
                            && !string.IsNullOrEmpty(a.MediaFile)
                            && !onDisk.Contains(a.MediaFile))
                .Select(a => a.Id)
                .ToList();

            foreach (var id in stale)
            {
                cfg.Advertisements.RemoveAll(a => a.Id == id);
                cfg.Statistics.RemoveAll(s => s.AdvertisementId == id);
                result.RemovedMissing++;
            }

            if (files.Count == 0)
            {
                if (result.RemovedMissing > 0)
                {
                    Save();
                }

                _logger.LogInformation(
                    "[StartupAds] Scan: no compatible files. Removed {Removed} stale auto ad(s).",
                    result.RemovedMissing);
                return result;
            }

            var existing = new HashSet<string>(
                cfg.Advertisements.Select(a => a.MediaFile),
                StringComparer.OrdinalIgnoreCase);

            var created = 0;
            var order = cfg.Advertisements.Count == 0 ? 0 : cfg.Advertisements.Max(a => a.Order);

            foreach (var file in files)
            {
                if (existing.Contains(file.FileName))
                {
                    continue;
                }

                order++;
                cfg.Advertisements.Add(new Advertisement
                {
                    Id = Guid.NewGuid(),
                    Name = file.FileName,
                    Type = file.Type,
                    Title = string.Empty,
                    MediaFile = file.FileName,
                    DurationMode = file.Type == AdvertisementType.Video
                        ? AdDurationMode.FromVideo
                        : AdDurationMode.Manual,
                    DurationSeconds = cfg.DefaultDurationSeconds,
                    Priority = 5,
                    Order = order,
                    Enabled = true,
                    ShowOnStartup = true,
                    AllowSkip = cfg.AllowSkip,
                    SkipAfterSeconds = cfg.SkipAfterSeconds,
                    ShowCountdown = cfg.ShowCountdown,
                    ObjectFit = cfg.ObjectFit,
                    AutoGenerated = true
                });
                created++;
            }

            result.Imported = created;

            if (created > 0 || result.RemovedMissing > 0)
            {
                Save();
            }

            _logger.LogInformation(
                "[StartupAds] Scan: imported {Imported} new ad(s), removed {Removed} stale auto ad(s).",
                result.Imported,
                result.RemovedMissing);
            return result;
        }

        /// <summary>
        /// Returns the ordered list of advertisements that should be shown right now for the
        /// given user, honouring source mode, schedule, targeting, ordering and the per-startup cap.
        /// </summary>
        public IReadOnlyList<Advertisement> GetActiveForUser(Guid userId, DateTime nowLocal)
        {
            var cfg = Config;
            return Select(cfg.Advertisements, cfg, userId, nowLocal, a => HasUsableMedia(a, cfg));
        }

        /// <summary>
        /// Pure selection pipeline (no I/O, no plugin singleton) so it can be unit-tested:
        /// source-mode filter → enabled/startup → schedule → user targeting → media availability
        /// → ordering (priority desc / name / manual / random) → optional single random pick
        /// → <see cref="PluginConfiguration.MaxAdsPerStartup"/> cap.
        /// </summary>
        public static IReadOnlyList<Advertisement> Select(
            IEnumerable<Advertisement> ads,
            PluginConfiguration cfg,
            Guid userId,
            DateTime nowLocal,
            Func<Advertisement, bool> hasMedia)
        {
            if (!cfg.Enabled || !cfg.ShowOnStartup)
            {
                return Array.Empty<Advertisement>();
            }

            IEnumerable<Advertisement> pool = cfg.SourceMode switch
            {
                AdSourceMode.Manual => ads.Where(a => !a.AutoGenerated),
                AdSourceMode.Automatic => ads.Where(a => a.AutoGenerated),
                _ => ads
            };

            var candidates = pool
                .Where(a => a.Enabled && a.ShowOnStartup)
                .Where(a => IsWithinSchedule(a, nowLocal))
                .Where(a => IsUserTargeted(a, userId))
                .Where(a => a.Type == AdvertisementType.Text || hasMedia(a))
                .ToList();

            if (candidates.Count == 0)
            {
                return Array.Empty<Advertisement>();
            }

            candidates = cfg.OrderMode switch
            {
                AdOrderMode.Priority => candidates.OrderByDescending(a => a.Priority).ThenBy(a => a.Order).ToList(),
                AdOrderMode.Name => candidates.OrderBy(a => a.Name, StringComparer.OrdinalIgnoreCase).ToList(),
                AdOrderMode.Manual => candidates.OrderBy(a => a.Order).ToList(),
                AdOrderMode.Random => Shuffle(candidates),
                _ => candidates
            };

            if (cfg.RandomPick && candidates.Count > 1)
            {
                candidates = new List<Advertisement> { candidates[Random.Shared.Next(candidates.Count)] };
            }

            var max = Math.Max(1, cfg.MaxAdsPerStartup);
            return candidates.Take(max).ToList();
        }

        private bool HasUsableMedia(Advertisement a, PluginConfiguration cfg)
            => _files.ResolveFile(cfg.AdsDirectory, a.MediaFile) is not null;

        public static bool IsWithinSchedule(Advertisement a, DateTime nowLocal)
        {
            if (a.StartDate is { } sd && nowLocal.Date < sd.Date)
            {
                return false;
            }

            if (a.EndDate is { } ed && nowLocal.Date > ed.Date)
            {
                return false;
            }

            if (a.DaysOfWeek.Count > 0 && !a.DaysOfWeek.Contains((int)nowLocal.DayOfWeek))
            {
                return false;
            }

            return IsWithinTimeWindow(a.StartTime, a.EndTime, nowLocal.TimeOfDay);
        }

        /// <summary>
        /// Inclusive time-of-day window. When <paramref name="end"/> is earlier than
        /// <paramref name="start"/> the window is treated as crossing midnight
        /// (e.g. 22:00 → 02:00 matches 22:00, 23:59, 00:00, 01:59 and 02:00 but not 02:01).
        /// A missing bound means "no restriction on that side".
        /// </summary>
        public static bool IsWithinTimeWindow(string? start, string? end, TimeSpan now)
        {
            var hasStart = TryParseTime(start, out var st);
            var hasEnd = TryParseTime(end, out var et);

            if (!hasStart && !hasEnd)
            {
                return true;
            }

            if (hasStart && !hasEnd)
            {
                return now >= st;
            }

            if (!hasStart && hasEnd)
            {
                return now <= et;
            }

            // Both bounds present.
            if (st <= et)
            {
                return now >= st && now <= et;
            }

            // Crosses midnight.
            return now >= st || now <= et;
        }

        public static bool IsUserTargeted(Advertisement a, Guid userId)
            => a.AllowedUserIds.Count == 0
               || a.AllowedUserIds.Any(id => Guid.TryParse(id, out var g) && g == userId);

        private static bool TryParseTime(string? value, out TimeSpan ts)
        {
            ts = default;
            return !string.IsNullOrWhiteSpace(value)
                   && TimeSpan.TryParseExact(value, new[] { @"hh\:mm", @"h\:mm" }, CultureInfo.InvariantCulture, out ts);
        }

        private static List<Advertisement> Shuffle(List<Advertisement> input)
        {
            var arr = input.ToArray();
            for (var i = arr.Length - 1; i > 0; i--)
            {
                var j = Random.Shared.Next(i + 1);
                (arr[i], arr[j]) = (arr[j], arr[i]);
            }

            return arr.ToList();
        }

        // ---- Statistics ----

        /// <summary>The only tracking events the API accepts.</summary>
        public static readonly IReadOnlySet<string> TrackingEvents = new HashSet<string>(StringComparer.Ordinal)
        {
            "impression", "started", "completed", "skipped", "clicked"
        };

        public static bool IsValidTrackingEvent(string? kind)
            => kind is not null && TrackingEvents.Contains(kind);

        public void Track(Guid adId, string kind)
        {
            var cfg = Config;
            if (!cfg.EnableStatistics || !IsValidTrackingEvent(kind))
            {
                return;
            }

            var stat = cfg.Statistics.FirstOrDefault(s => s.AdvertisementId == adId);
            if (stat is null)
            {
                stat = new AdStat { AdvertisementId = adId };
                cfg.Statistics.Add(stat);
            }

            switch (kind)
            {
                case "impression": stat.Impressions++; break;
                case "started": stat.Started++; break;
                case "completed": stat.Completed++; break;
                case "skipped": stat.Skipped++; break;
                case "clicked": stat.Clicked++; break;
                default: return;
            }

            Save();
        }
    }
}
