using System;
using System.Collections.Generic;

namespace Jellyfin.Plugin.StartupAds.Configuration
{
    public enum AdvertisementType
    {
        Image = 0,
        Video = 1,
        Text = 2,
        Multimedia = 3
    }

    public enum AdButtonAction
    {
        None = 0,
        ExternalUrl = 1,
        JellyfinItem = 2,
        CloseOnly = 3
    }

    public enum AdDurationMode
    {
        Manual = 0,
        FromVideo = 1
    }

    /// <summary>
    /// A single advertisement definition. Stored inside
    /// <see cref="PluginConfiguration.Advertisements"/>.
    /// </summary>
    public class Advertisement
    {
        public Advertisement()
        {
            Id = Guid.NewGuid();
            Name = string.Empty;
            Type = AdvertisementType.Image;
            Title = string.Empty;
            Description = string.Empty;
            MediaFile = string.Empty;
            BackgroundFile = string.Empty;
            DurationMode = AdDurationMode.Manual;
            DurationSeconds = 10;
            Priority = 5;
            Order = 0;
            Enabled = true;
            ShowOnStartup = true;
            AllowSkip = true;
            SkipAfterSeconds = 5;
            ShowCountdown = true;
            ButtonText = string.Empty;
            ButtonAction = AdButtonAction.None;
            ButtonUrl = string.Empty;
            ButtonItemId = string.Empty;
            ObjectFit = "contain";
            AllowedUserIds = new List<string>();
            DaysOfWeek = new List<int>();
            AutoGenerated = false;
        }

        public Guid Id { get; set; }

        public string Name { get; set; }

        public AdvertisementType Type { get; set; }

        public string Title { get; set; }

        /// <summary>Plain text / limited markdown. Sanitized on the client before rendering.</summary>
        public string Description { get; set; }

        /// <summary>File name (not a path) relative to the configured ads directory.</summary>
        public string MediaFile { get; set; }

        /// <summary>Optional background image file name for text ads.</summary>
        public string BackgroundFile { get; set; }

        public AdDurationMode DurationMode { get; set; }

        public int DurationSeconds { get; set; }

        /// <summary>Higher number = higher priority (shown first). Range 0–1000.</summary>
        public int Priority { get; set; }

        public int Order { get; set; }

        public bool Enabled { get; set; }

        public bool ShowOnStartup { get; set; }

        public bool AllowSkip { get; set; }

        public int SkipAfterSeconds { get; set; }

        public bool ShowCountdown { get; set; }

        public string ButtonText { get; set; }

        public AdButtonAction ButtonAction { get; set; }

        public string ButtonUrl { get; set; }

        /// <summary>Jellyfin item id used when <see cref="ButtonAction"/> is <see cref="AdButtonAction.JellyfinItem"/>.</summary>
        public string ButtonItemId { get; set; }

        public string ObjectFit { get; set; }

        // ---- Scheduling ----
        public DateTime? StartDate { get; set; }

        public DateTime? EndDate { get; set; }

        /// <summary>0=Sunday .. 6=Saturday. Empty = every day.</summary>
        public List<int> DaysOfWeek { get; set; }

        /// <summary>
        /// "HH:mm" local time, inclusive. Null/empty = no restriction. When
        /// <see cref="EndTime"/> is earlier than <see cref="StartTime"/> the window
        /// is treated as crossing midnight (e.g. 22:00 → 02:00).
        /// </summary>
        public string? StartTime { get; set; }

        /// <summary>"HH:mm" local time, inclusive. Null/empty = no restriction.</summary>
        public string? EndTime { get; set; }

        // ---- Targeting ----
        /// <summary>Empty = all users. Otherwise only these Jellyfin user ids (string form).</summary>
        public List<string> AllowedUserIds { get; set; }

        public bool AutoGenerated { get; set; }
    }
}
