using System;
using System.Collections.Generic;
using System.Linq;
using Jellyfin.Plugin.StartupAds.Configuration;
using Jellyfin.Plugin.StartupAds.Services;
using Xunit;

namespace Jellyfin.Plugin.StartupAds.Tests
{
    public class SelectionTests
    {
        private static readonly DateTime Now = new(2026, 9, 15, 12, 0, 0);
        private static readonly Guid User = Guid.Parse("11111111-1111-1111-1111-111111111111");
        private static readonly Guid OtherUser = Guid.Parse("22222222-2222-2222-2222-222222222222");

        private static PluginConfiguration Cfg(Action<PluginConfiguration>? tweak = null)
        {
            var c = new PluginConfiguration
            {
                Enabled = true,
                ShowOnStartup = true,
                OrderMode = AdOrderMode.Priority,
                SourceMode = AdSourceMode.Mixed,
                MaxAdsPerStartup = 10,
                RandomPick = false
            };
            tweak?.Invoke(c);
            return c;
        }

        private static Advertisement Text(string name, int priority = 5, bool enabled = true) => new()
        {
            Name = name,
            Type = AdvertisementType.Text,
            Title = name,
            Priority = priority,
            Enabled = enabled,
            ShowOnStartup = true
        };

        private static IReadOnlyList<Advertisement> Run(IEnumerable<Advertisement> ads, PluginConfiguration cfg, Guid user)
            => AdvertisementManager.Select(ads, cfg, user, Now, _ => true);

        [Fact]
        public void DisabledAdsAreExcluded()
        {
            var ads = new[] { Text("a"), Text("b", enabled: false) };
            var result = Run(ads, Cfg(), User);
            Assert.Single(result);
            Assert.Equal("a", result[0].Name);
        }

        [Fact]
        public void PriorityHigherNumberWinsFirst()
        {
            var ads = new[] { Text("low", 10), Text("high", 100), Text("mid", 50) };
            var result = Run(ads, Cfg(), User);
            Assert.Equal(new[] { "high", "mid", "low" }, result.Select(a => a.Name).ToArray());
        }

        [Fact]
        public void UserTargetingRespected()
        {
            var targeted = Text("targeted");
            targeted.AllowedUserIds.Add(User.ToString());
            var ads = new[] { targeted, Text("everyone") };

            Assert.Equal(2, Run(ads, Cfg(), User).Count);
            Assert.Equal(new[] { "everyone" }, Run(ads, Cfg(), OtherUser).Select(a => a.Name).ToArray());
        }

        [Fact]
        public void OutOfScheduleExcluded()
        {
            var expired = Text("expired");
            expired.EndDate = new DateTime(2026, 1, 1);
            var ads = new[] { expired, Text("current") };
            var result = Run(ads, Cfg(), User);
            Assert.Equal(new[] { "current" }, result.Select(a => a.Name).ToArray());
        }

        [Fact]
        public void MaxAdsPerStartupCapsResult()
        {
            var ads = new[] { Text("a", 3), Text("b", 2), Text("c", 1) };
            var result = Run(ads, Cfg(c => c.MaxAdsPerStartup = 2), User);
            Assert.Equal(2, result.Count);
            Assert.Equal(new[] { "a", "b" }, result.Select(a => a.Name).ToArray());
        }

        [Fact]
        public void RandomPickReturnsExactlyOneEligibleAd()
        {
            var ads = new[] { Text("a"), Text("b"), Text("c") };
            for (var i = 0; i < 20; i++)
            {
                var result = Run(ads, Cfg(c => c.RandomPick = true), User);
                Assert.Single(result);
                Assert.Contains(result[0].Name, new[] { "a", "b", "c" });
            }
        }

        [Fact]
        public void RandomPickNeverReturnsIneligibleAd()
        {
            var disabled = Text("disabled", enabled: false);
            var expired = Text("expired");
            expired.EndDate = new DateTime(2020, 1, 1);
            var wrongUser = Text("wrongUser");
            wrongUser.AllowedUserIds.Add(OtherUser.ToString());
            var ok = Text("ok");

            var ads = new[] { disabled, expired, wrongUser, ok };
            for (var i = 0; i < 20; i++)
            {
                var result = Run(ads, Cfg(c => c.RandomPick = true), User);
                Assert.Single(result);
                Assert.Equal("ok", result[0].Name);
            }
        }

        [Fact]
        public void MediaMissingExcludesNonTextAd()
        {
            var img = new Advertisement
            {
                Name = "img", Type = AdvertisementType.Image, Enabled = true,
                ShowOnStartup = true, MediaFile = "gone.jpg"
            };
            var ads = new[] { img, Text("text") };
            var result = AdvertisementManager.Select(ads, Cfg(), User, Now, a => a.Type == AdvertisementType.Text);
            Assert.Equal(new[] { "text" }, result.Select(a => a.Name).ToArray());
        }

        [Fact]
        public void SourceModeManualExcludesAutoGenerated()
        {
            var auto = Text("auto");
            auto.AutoGenerated = true;
            var ads = new[] { auto, Text("manual") };
            var result = Run(ads, Cfg(c => c.SourceMode = AdSourceMode.Manual), User);
            Assert.Equal(new[] { "manual" }, result.Select(a => a.Name).ToArray());
        }

        [Fact]
        public void SourceModeAutomaticExcludesManuallyCreated()
        {
            var auto = Text("fromScan");
            auto.AutoGenerated = true;                 // creado por "Escanear"
            var manual = Text("byHand");               // creado a mano  -> AutoGenerated=false
            var ads = new[] { auto, manual };
            var result = Run(ads, Cfg(c => c.SourceMode = AdSourceMode.Automatic), User);
            Assert.Equal(new[] { "fromScan" }, result.Select(a => a.Name).ToArray());
        }

        [Fact]
        public void SourceModeMixedShowsBoth()
        {
            var auto = Text("fromScan");
            auto.AutoGenerated = true;
            var ads = new[] { auto, Text("byHand") };
            var result = Run(ads, Cfg(c => c.SourceMode = AdSourceMode.Mixed), User);
            Assert.Equal(2, result.Count);
        }

        [Fact]
        public void PluginDisabledReturnsNothing()
        {
            var ads = new[] { Text("a") };
            Assert.Empty(Run(ads, Cfg(c => c.Enabled = false), User));
        }
    }
}
